title : Lecture Notes on Fundamental of Data Analysis
author: Antonino Furnari
logo: 'logo.png'

# Short description about the book
description: >-
  Lecture Notes on Fundamental of Data Analysis

execute:
  execute_notebooks           : 'off'

# HTML-specific settings
html:
  home_page_in_navbar         : false
  favicon                     : 'favicon.ico'


# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/antoninofurnari/fadlecturenotes
  path_to_book                : "lecturenotes/"
  branch                      : "master"

launch_buttons:
  colab_url: "https://colab.research.google.com"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - sphinxcontrib.mermaid
  # config:
  #   html_theme_options:
  #       use_download_button: false
  #       repository_url: https://github.com/antoninofurnari/fadlecturenotes/
  #       use_issues_button: true